Repository extinctionfighters/initiatives, pull requests merged in 2019-08, with the labels that each got.

#2 Add description, press and actions
  data.js
Labels: extinction-rebellion

#3 Description, countries, employees and income for ClientEarth
  data.js
Labels: client-earth

#4 Wwf first information
  data.js
Labels: wwf

#5 Add basic information for Sierra Club
  data.js
Labels: sierra-club

#8 Basic information for WWF and Greenpeace
  data.js
Labels: greenpeace, wwf

#7 adds basic information on ClimateWorks
  data.js
  package.json
Labels: climateworks
